# Generated by Django 5.0.6 on 2024-05-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
