# Generated by Django 5.0.6 on 2024-05-11 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customer_role_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RestaurantVerified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=50)),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
