# Generated by Django 5.0.6 on 2024-05-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_restaurant_address_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantverified',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='varified_restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurantverified'),
        ),
        migrations.AlterField(
            model_name='restaurantverified',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='initiated', max_length=50),
        ),
    ]
