# Generated by Django 5.0.6 on 2024-05-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_restaurantverified_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantverified',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('initiated', 'Initiated'), ('approved', 'Approved')], default='initiated', max_length=50),
        ),
    ]
