# Generated by Django 5.0.6 on 2024-05-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_restaurantverified_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantverified',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('initiated', 'Initiated'), ('rejected', 'Rejected')], default='initiated', max_length=50),
        ),
    ]
