# Generated by Django 5.0.6 on 2024-05-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_restaurant_menuitem_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='restaurant_Id',
            new_name='restaurant',
        ),
    ]
